<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGSjxm76\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGSjxm76/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGSjxm76.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGSjxm76\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGSjxm76\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GSjxm76',
    'container.build_id' => '4dc9999c',
    'container.build_time' => 1611152449,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGSjxm76');
